<?php

namespace ImmoNotaire\ImmoAnnonceBundle\Repository;

/**
 * Annonce_localRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Annonce_localRepository extends \Doctrine\ORM\EntityRepository {

    public function rechercheLocal(array $param) {

        $query = $this->createQueryBuilder('a')
                ->leftJoin('a.annonce', 'news')
                ->addSelect('news');

        $query->where($query->expr()->orX($query->expr()->eq('news.type_annonce', ':typeannonce')))
                ->setParameter('typeannonce', $param['type_annonce'])
                ->andWhere($query->expr()->orX($query->expr()->eq('news.active', ':active')))
                ->setParameter('active', 1) //active
                ->andWhere($query->expr()->orX($query->expr()->eq('news.supprimer', ':supprimer')))
                ->setParameter('supprimer', 0); // supprimé
        if (!empty($param['ville'])) {
            $query->andWhere($query->expr()->orX($query->expr()->eq('news.ville', ':ville')))
                    ->setParameter('ville', $param['ville']); //ville
        }
        if (!empty($param['type_biens'])) {
            $query->andWhere($query->expr()->orX($query->expr()->eq('news.type_biens', ':typeBiens')))
                    ->setParameter('typeBiens', $param['type_biens']); //appart ou autre
        }
        if (!empty($param['type_local'])) {
            $query->andWhere($query->expr()->orX($query->expr()->eq('a.type_local', ':typeLocal')))
                    ->setParameter('typeLocal', $param['type_local']); //appart ou autre
        }

        if (!empty($param['superficie'])) {
            $query->andWhere($query->expr()->orX($query->expr()->eq('a.superficie', ':superficie')))
                    ->setParameter('superficie', $param['superficie']);
        }
        if (!empty($param['piece'])) {
            $query->andWhere($query->expr()->orX($query->expr()->eq('a.piece', ':piece')))
                    ->setParameter('piece', $param['piece']);
        }
        if (!empty($param['prix'])) {
            $query->andWhere($query->expr()->orX($query->expr()->lte('news.prix', ':prix')))
                    ->setParameter('prix', $param['prix']);
        }

        return $query->getQuery()->getResult();
    }

}
