<?php

namespace ImmoNotaire\ImmoAnnonceBundle\Repository;

/**
 * Type_localRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_localRepository extends \Doctrine\ORM\EntityRepository
{
}
