<?php

namespace ImmoNotaire\ImmoAnnonceBundle\Repository;

/**
 * Type_BiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_biensRepository extends \Doctrine\ORM\EntityRepository
{
}
