# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

     Immo_Upload_listener:
            class: ImmoNotaire\ImmoAnnonceBundle\EventListener\UploadListener
            arguments: ['@Immo_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postLoad }
