annonce_index:
    path:     /
    defaults: { _controller: "ImmoAnnonceBundle:Annoncecrud:index" }
    methods:  GET

annonce_show:
    path:     /{id}/show
    defaults: { _controller: "ImmoAnnonceBundle:Annoncecrud:show" }
    methods:  GET

annonce_new:
    path:     /new
    defaults: { _controller: "ImmoAnnonceBundle:Annoncecrud:new" }
    methods:  [GET, POST]

annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "ImmoAnnonceBundle:Annoncecrud:edit" }
    methods:  [GET, POST]

annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "ImmoAnnonceBundle:Annoncecrud:delete" }
    methods:  DELETE
