annonce_terrain_index:
    path:     /
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_terrain:index" }
    methods:  GET

annonce_terrain_show:
    path:     /{id}/show
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_terrain:show" }
    methods:  GET

annonce_terrain_new:
    path:     /new
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_terrain:new" }
    methods:  [GET, POST]

annonce_terrain_edit:
    path:     /{id}/edit
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_terrain:edit" }
    methods:  [GET, POST]

annonce_terrain_delete:
    path:     /{id}/delete
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_terrain:delete" }
    methods:  DELETE
