annonce_appart_index:
    path:     /
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_appart:index" }
    methods:  GET

annonce_appart_show:
    path:     /{id}/show
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_appart:show" }
    methods:  GET

annonce_appart_new:
    path:     /new
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_appart:new" }
    methods:  [GET, POST]

annonce_appart_edit:
    path:     /{id}/edit
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_appart:edit" }
    methods:  [GET, POST]

annonce_appart_delete:
    path:     /{id}/delete
    defaults: { _controller: "ImmoAnnonceBundle:Annonce_appart:delete" }
    methods:  DELETE
