publicite_publicite:
    resource: "@PubliciteBundle/Resources/config/routing/publicite.yml"
    prefix:   /publicite

publicite_homepage:
    path:     /
    defaults: { _controller: PubliciteBundle:Default:index }
